version: "3.9"
services:
  web-api:
    build: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    networks:
      - mc_network
networks:
  mc_network:
    external: true