version: "3.9"
services:
  web-api:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/src
    ports:
      - "8000:8000"